#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/907ffeb0-9ad2-49cf-b84c-54682ada86a5 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight eye1;
  CloudLight eye2;
  CloudTemperatureSensor temperature;
  CloudRelativeHumidity humidity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  pinMode(15,OUTPUT);
  pinMode(5,OUTPUT);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


/*
  Since Eye1 is READ_WRITE variable, onEye1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onEye1Change()  {
if (eye1==1){
  digitalWrite(15,HIGH);

  
}
  else{
    digitalWrite(15,LOW);
  }
}


/*
  Since Eye2 is READ_WRITE variable, onEye2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onEye2Change()  {
if (eye2==1){
  digitalWrite(5,HIGH);

  
}
  else{
    digitalWrite(5,LOW);
  }}

